services:
  - type: web
    name: assistant-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn assistant:app --workers 2 --threads 4 --bind 0.0.0.0:$PORT
